# Generated by Django 4.2.7 on 2023-12-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_contato_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
