# Generated by Django 4.2.7 on 2023-12-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_contato_update_date_alter_contato_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='picture',
        ),
    ]
