# Generated by Django 4.2.7 on 2023-12-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_contato_update_date_alter_contato_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'Oportunidade',
            },
        ),
    ]
